config/routes.rb
Rails.application.routes.draw do
    root 'gossips#index'
    get 'static_pages/team'
    get 'static_pages/contact'

    resources :gossips
    resources :likes
    resources :users
    resources :cities
    resources :comments
    resources :sessions, only: [:new, :create, :destroy]
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_one :city, through: :user
    has_many :comments
    validates :title, presence: true, length: { in: 3..13 }
    validates :content, presence: true
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
    #before_action
    before_action :authenticate_user, only: [:index]
    before_action :user_is_op, only: [:edit, :update, :destroy]

    def index
        @gossips = Gossip.all
        @likes = Like.all
    end

    def show
        @gossips = Gossip.find(params[:id])
        @likes = Like.all
        @comment = @gossips.comments
    end

    def new
        @gossips = Gossip.new
    end

    def create
        user = User.find_by(id: session[:user_id])
        @gossips = Gossip.new(title: params[:title], content: params[:content], user_id: user.id)   
        if @gossips.save 
            redirect_to gossips_path 
        else
            render inline: @gossips.errors.full_messages 
        end
    end

    def edit
        @gossips = Gossip.find(params[:id])
    end

    def update
        @gossips = Gossip.find(params[:id])
        if @gossips.update(title: params[:title], content: params[:content])
         redirect_to "/"
        else
           render :edit
        end
    end

    def destroy
        @gossips = Gossip.find(params[:id])
        @gossips.destroy
        redirect_to gossips_path
    end

    private

    def authenticate_user
      unless session[:user_id]
        flash[:danger] = "Please log in."
        redirect_to new_session_path
      end
    end

    def user_is_op
        puts "****"
        puts session[:user_id]
        puts "****"
        unless session[:user_id] == Gossip.find(params[:id]).user.id
          flash[:danger] = "You cant do that !"
          redirect_to new_session_path
        end
      end
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<h1>Edit a gossip</h1>

 <!--   <%= form_for :gossips do |f| %>
        <div class="form-group">
            <label>Title</label>
            <%= f.text_field :title, class: 'form-control'%>
        </div><br>
        <div class="form-group">
            <label>Content</label>
            <%= f.text_field :content, class: 'form-control'%>
        </div><br>
        <div class="form-group">
            <button type="submit">Edit gossip</button>
        </div><br>
    <% end %>

-->


 <%= form_tag url_for(action: 'update'), method: "put" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', @gossips.title %>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'content', @gossips.content %>
      <br /> <br />

      <%= submit_tag "Edit Post" %>

<% end %>

app/views/gossips/index.html.erb
<h1>Welcome to The Gossip Project</h1>
<p></p>
    <a href= "<%= new_gossip_path %>" class="btn btn-primary btn-lg text-decoration-none link-light">Create a new gossip !</a>
<p></p>
<h3>The lasts gossips:</h3>
<p></p>
<div class="container-fluid d-flex flex-wrap justify-content-center row xy-3">
    <% @gossips.each do |gossip| %>
        <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title"><%= gossip.title %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= gossip.user.first_name %></h6>
            <p class="card-text"><%= gossip.content %></p>
            <a href="/gossips/<%= gossip.id %>" class="btn btn-primary btn-sm">Details</a>
            <a href="/users/<%= gossip.user.id %>" class="btn btn-secondary btn-sm">Author</a>
            <a href="/cities/<%= gossip.user.city_id %>" class="btn btn-success btn-sm">City</a>
            <p></p>
            <p class="card-text"><a href="/likes/<%= gossip.id %>" class="btn btn-danger btn-sm"> Like! </a><FONT color="#fcba03"><B><I><%= " " + @likes.where(gossip: gossip).count.to_s + " likes !" %></B></I></FONT></p>
        </div>
        </div>
    <%end%>
</div>

app/views/gossips/new.html.erb
<h1>The Gossip Project</h1>

<h3>Publish a new gossip:</h3>

 <%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', @gossips.title %>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'content', @gossips.content %>
      <br /> <br />

      <%= submit_tag "Create Post" %>

    <% end %>

app/views/gossips/show.html.erb
<h1>Gossip detail</h1>
<h3>Gossip page n°<%= params["id"] %></h3>
    <div class="card centered-element" style="width: 12rem;">
        <div class="card-body">
            <h5 class="card-title">Title: <%= @gossips.title %></h5>
            <h6 class="card-subtitle mb-2 text-muted">Author: <%= @gossips.user.first_name%></h6>
            <p class="card-text">Content: <%= @gossips.content %></p>
            <a href= "<%= edit_gossip_path(@gossips.id) %>" class="btn btn-primary text-decoration-none link-light">Edit</a>
            <%= link_to "Delete", gossip_path, method: :delete, class: "btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            <p></p>
            <p class="card-text"><a href="/likes/<%= @gossips.id %>" class="btn btn-danger btn-sm"> Like! </a><FONT color="#fcba03"><B><I><%= " " + @likes.where(gossip: @gossips).count.to_s + " likes !" %></B></I></FONT></p>
        </div>
    </div>

<br/>

<%= form_tag(comments_path, method: 'post') do %>
  <%= hidden_field_tag('gossip_id', params[:id] )%>
  <%= text_area_tag 'content', nil %>
  <br /> <br />

  <%= submit_tag "Comment", class: "btn btn-secondary " %>


    <% @comment.each do |comm| %>
    <article> 
        <h4 class="desc-title">Comment of <%= comm.user.first_name %> </h4>
        <p class="desc"><%= comm.content %></p>
        <div class="show-edit">
            <%= link_to 'Modifier', edit_comment_path(comm.id), class:'btn btn-secondary', data: { "turbo-method": :edit } %>
            <%= link_to 'Supprimer', comment_path(comm.id), class:"btn btn-outline-danger", data: { "turbo-method": :delete } %>
        </div>
    </article>         
    <% end %>
<% end %>